import dotalogo from "./images/Dota logo-01.png";
import image1 from "../../assets/home/KnowYourSUC/IMG_9707-removebg-preview (1).png";

export const dota = {
  Name: {
    logo: `${dotalogo}`,
    name: "Department of Technical Art",
    aboutHeading: "About us",
    aboutPara:
      "  Lorem ipsum dolor sit amet consectetur adipisicing elit. Impeditullam, sunt ea quibusdam quisquam eveniet, reprehenderit laboriosamcorporis in ipsam tenetur aut saepe iste, illum rerum voluptatesfacere temporibus nihil doloribus mollitia dicta nulla quae commodi.Blanditiis recusandae, non atque autem temporibus beatae, iuredignissimos suscipit, itaque quas architecto nemo?",
  },
  events: [
    {
      id: "first",
      date: 22,
      month: "August",
      heading: "Campus Event Headline",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",

      color: "rgb(218, 37, 29)",
    },
    {
      id: "second",
      date: 23,
      month: "August",
      heading: "Campus Event Headline",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
      color: "#45b43b",
    },
    {
      id: "third",
      date: 24,
      month: "August",
      heading: "Campus Event Headline",
      color: " #2d7dd2",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },
    {
      id: "fourth",
      date: 25,
      month: "August",
      heading: "Campus Event Headline",
      color: "#ffc300",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },

    {
      id: "fiveth",
      date: 26,
      month: "August",
      heading: "Campus Event Headline",
      color: "#2d7dd2",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },
    {
      id: "sixth",
      date: 27,
      month: "August",
      heading: "Campus Event Headline",
      color: "#ffc300",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },
    {
      id: "seventh",
      date: 28,
      month: "August",
      heading: "Campus Event Headline",
      color: "rgb(218, 37, 29)",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },
    {
      id: "eight",
      date: 29,
      month: "August",
      heading: "Campus Event Headline",
      color: "#45b43b",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },
    {
      id: "nineth",
      date: 30,
      month: "August",
      heading: "Campus Event Headline",
      color: "#45b43b",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },
    {
      id: "tenth",
      date: 31,
      month: "August",
      heading: "Campus Event Headline",
      color: "rgb(218, 37, 29)",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },
    {
      id: "eleventh",
      date: 1,
      month: "August",
      heading: "Campus Event Headline",
      color: "rgb(218, 37, 29)",
      para: "     Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptates, ipsa earum? Magni cumque quis ex minus, eveniet ametprovident quas ratione cum aperiam, dolor velit impedit facerequisquam? Quos, error.",
    },
  ],
};
export const PorHolders = [
  {
    name: "Krishna Prawjal S 1",
    post: "president1",
    image: `${image1}`,
    insta: "https://www.instagram.com/bitspilaniofficial/",
    linkedin: "https://www.instagram.com/bitspilaniofficial/",
    facebook: "https://www.instagram.com/bitspilaniofficial/",
    image_width: "268.462",
    image_height: "244.85",
  },
  {
    name: "Krishna Prawjal S 1",
    post: "president1",
    image: `${image1}`,
    insta: "https://www.instagram.com/bitspilaniofficial/",
    linkedin: "https://www.instagram.com/bitspilaniofficial/",
    facebook: "https://www.instagram.com/bitspilaniofficial/",
    image_width: "268.462",
    image_height: "244.85",
  },
  {
    name: "Krishna Prawjal S 2",
    post: "president2",
    image: `${image1}`,
    insta: "https://www.instagram.com/bitspilaniofficial/",
    linkedin: "https://www.instagram.com/bitspilaniofficial/",
    facebook: "https://www.instagram.com/bitspilaniofficial/",
    image_width: "268.462",
    image_height: "244.85",
  },
];
